name: Release-build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      # - feature/cicd-adjusts

jobs:
  build_and_release:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests esptool

      - name: Set Build Number in platformio.ini
        run: sed -i "s/\[_BUILD_NUMBER_\]/v0.0.${{ github.run_number }}/g" platformio.ini

      - name: Install PlatformIO Core
        run: |
          pip install platformio
          platformio update

      - name: Build Project
        run: |
          platformio run

      - name: Merge output binaries files
        run: |
          esptool.py --chip esp32 merge_bin -o .pio/build/m5stack-cplus1_1/release.bin --flash_mode dio --flash_size 4MB 0x1000 .pio/build/m5stack-cplus1_1/bootloader.bin 0x8000 .pio/build/m5stack-cplus1_1/partitions.bin 0x10000 .pio/build/m5stack-cplus1_1/firmware.bin
          esptool.py --chip esp32 merge_bin -o .pio/build/m5stack-cplus2/release.bin --flash_mode dio --flash_size 8MB 0x1000 .pio/build/m5stack-cplus2/bootloader.bin 0x8000 .pio/build/m5stack-cplus2/partitions.bin 0x10000 .pio/build/m5stack-cplus2/firmware.bin
          esptool.py --chip esp32s3 merge_bin -o .pio/build/m5stack-cardputer/release.bin --flash_mode dio --flash_size 8MB 0x0000 .pio/build/m5stack-cardputer/bootloader.bin 0x8000 .pio/build/m5stack-cardputer/partitions.bin 0x10000 .pio/build/m5stack-cardputer/firmware.bin

      - name: Rename release.bin files
        run: |
          for file in $(find .pio/build/**/ -name 'release.bin'); do
            version=$(echo ${{ github.run_number }})
            env=$(basename $(dirname "$file"))
            new_name="ESP_Web2Sd-Mgr_${env}_v0.0.$version.bin"
            mv "$file" "$(dirname "$file")/$new_name"
          done
          chmod +r .pio/build/**/ESP_Web2Sd-Mgr*.bin
          ls .pio/build/**/ESP_Web2Sd-Mgr*.bin
        if: github.event_name != 'pull_request'

      - name: Upload Binaries
        id: upload_binaries
        uses: actions/upload-artifact@v3
        with:
          path: .pio/build/**/ESP_Web2Sd-Mgr*.bin
        if: github.event_name != 'pull_request'

      - name: Copy binaries to root folder
        run: |
          set -x
          pwd 
          for file in $(find .pio/build/** -name 'ESP_Web2Sd-Mgr*.bin'); do
            echo "Copying $file to root folder"
            cp "$file" .
          done
          ls -all
          tree
          
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v0.0.${{ github.run_number }}
          release_name: v0.0.${{ github.run_number }}
          draft: true
          prerelease: false
          body: |
            Release automatically generated by CI/CD workflow.
            
      - name: Update Release with assets
        uses: softprops/action-gh-release@v1
        with:
          name: Release
          tag_name: v0.0.${{ github.run_number }}
          generate_release_notes: true
          files: |
            ESP_Web2Sd-Mgr*.bin
        
